feat(CB2-6750): View Plates
dvsa/cvs-svc-document-retrieval pull request #40
Opened 2023-02-03 16:16 UTC by leifkemp-bjss

## PR to allow document retrieval to fetch plates

Splits certificate and plate service into two, and bumps a few packages to fix vulnerabilities where possible
[CB2-6750](https://dvsa.atlassian.net/browse/CB2-6750)

## Checklist
- [ ] Code has been tested manually
- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Squashed commit contains the JIRA ticket number

2023-02-03 16:35 UTC, tom-bjss requested changes
I think a simpler solution can achieve what we need without infra changes needed aswell, will discuss Monday.

2023-02-06 10:40 UTC, tom-bjss approved these changes

2023-02-06 10:52 UTC, naathanbrown approved these changes

2023-02-06 15:47 UTC, leifkemp-bjss commented
Closing this PR as I'm working on feature/CB2-6750 instead for deployment reasons

2023-02-06 15:47 UTC, closed without merging